// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {api} from '../models';

export function ApplyResource(arg1:string,arg2:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetApiResources(arg1:string):Promise<main.APIResourceMap>;

export function GetClusters():Promise<{[key: string]: api.Context}>;

export function GetDefaultNamespace(arg1:string):Promise<string>;

export function GetEvents(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetNamespaces(arg1:string):Promise<Array<string>>;

export function GetPodContainerLogs(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetResourceDependencies(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.DependencyChain>;

export function GetResourceYAML(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetResourcesInNamespace(arg1:string,arg2:string,arg3:string):Promise<Array<any>>;

export function StartWebSocketServer():Promise<void>;

export function TestClusterConnectivity(arg1:string):Promise<boolean>;
