// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyResource(arg1, arg2) {
  return window['go']['main']['App']['ApplyResource'](arg1, arg2);
}

export function DeleteResource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteResource'](arg1, arg2, arg3, arg4);
}

export function GetApiResources(arg1) {
  return window['go']['main']['App']['GetApiResources'](arg1);
}

export function GetClusters() {
  return window['go']['main']['App']['GetClusters']();
}

export function GetDefaultNamespace(arg1) {
  return window['go']['main']['App']['GetDefaultNamespace'](arg1);
}

export function GetEvents(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetEvents'](arg1, arg2, arg3, arg4);
}

export function GetNamespaces(arg1) {
  return window['go']['main']['App']['GetNamespaces'](arg1);
}

export function GetPodContainerLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPodContainerLogs'](arg1, arg2, arg3, arg4);
}

export function GetResourceYAML(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetResourceYAML'](arg1, arg2, arg3, arg4);
}

export function GetResourcesInNamespace(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetResourcesInNamespace'](arg1, arg2, arg3);
}

export function StartWebSocketServer() {
  return window['go']['main']['App']['StartWebSocketServer']();
}

export function TestClusterConnectivity(arg1) {
  return window['go']['main']['App']['TestClusterConnectivity'](arg1);
}
